---
title: "Financial Conditions and the Business Cycle"
subtitle: "Brown Macro Breakfast"
title-note: "^1^The views expressed here are the authors’ and are not necessarily representative of the views of the International Monetary Fund, its Management, or its Executive Directors."
author:
  - name: "Tobias Adrian"
    affiliation: "International Monetary Fund^1^"
  - name: "Matthew DeHaven"
    affiliation: Brown University
  - name: "Fernando Duarte"
    affiliation: Brown University
date: "2024-02-21"
callout-appearance: minimal
editor:
  render-on-save: true
format:
  clean-revealjs:
    self-contained: true
---

## Goal for Presentation Today

Focus on the "story" of the project.

Last presentation before I start drafting the paper (3rd year paper).

- Only minor changes to analysis

- Looking for comments about...
   - structure
   - 

## Co-movement over the Business Cycle

Empirically, we observe co-movement across macro variables over the business cycle.

. . .

**Key Question:** What drives this co-movement?

- A single shock?
- A common propagation mechanism?

. . .

We will show:

- fianncial conditions also co-move with the business cycle

- financial conditions provide a compelling propagation mechanism

## The Business Cycle

Defined to be a cycle with a period of 6 to 32 quarters.

. . .

- Roughly the range of peak-to-peak NBER recession dates.

. . .

[Picture of NBER Recession peaks-to-peaks, > 1950]


## Co-movement in Macro Variables

Angeletos, Collard, and Dellas (2020) run a large VAR with 10 macro variables:

. . .

- Output, Unemployment, Investment, Hours Worked, Consumption
- Inflation, Interest Rate, Labor Share, Productivity, TFP

. . .

... and identify a single shock using the max-share identification method.


## Max Share Identification Method

Choose the single shock that explains the largest share of the unforecasted variation in 

**(1) unemployment** at the 

**(2) business cycle frequency**.

. . .

:::{.callout-note}
Both (1) and (2) can be changed to target different variables or frequencies.
:::

. . .

They call this shock the "main business cycle shock".

## The Main Business Cycle Shock

The shock looks like a homoskedastic, mean-zero shock

[picture of shock] [histogram of shock]

. . .

But the structure of the VAR means the contribution of the shock to macro variables looks like the business cycle:

[Picture of business cycle for unemployment]


## The Main Business Cycle Shock

This business cycle shock also explains a large amount of the unforecasted variation in:

- Output, Investment, Hours Worked, and Consumption

. . .

[Table showing this]


## The Main Business Cycle Shock

If the shock was constructed targeting either

- Output, Investment, Hours Worked, or Consumption

The same "main business cycle shock" would be identified.

. . .

[Picture showing the correlations between the 4 shocks and unemployment one]

## The Main Business Cycle Shock

This is not the case for either

- Inflation or

- TFP

. . .

Thus the empirical business cycle does not align well with

- RBC productivity shocks or
- New Keynesian demand shocks.


## What Drives the Co-movement?

There are two possibilities:

. . .

1. A single shock

. . .

2. A common propagation mechanism

. . .

Angeletos, Collard, and Dellas (2020) suggest it could be driven by a single shock to "higher order beliefs".

. . .

We will show evidence for preferring financial conditions as a common propagation mechanism.


## Introducing the VFCI

Our preferred measure is the **volatility financial conditions index** constructed in Adrian, Duarte, and Iyer (2023).

. . .

The VFCI...

- can be interpreted as the *price of risk*
  - equivalent to the level of risk aversion of the aggregate housheold

[Picture of the VFCI with recession dates]


## Theory Behind the VFCI

The VFCI can be modeled with financial institutions that have a **value-at-risk** constraint.

. . .

- This constraint binds risk-taking in bad times, but not in good, creating a nonlinearity in the model.

. . .

- This nonlinearity links the mean and volatility in the model
  - This mean-vol relationship is also observed in the data

. . .

**Key:** The value-at-risk constraint aggregates all types of shocks in the model into a single constraint.


## Empirical Construction of the VFCI

Estimating the VFCI from forward GDP growth, $\Delta \text{gdp}_{t+h}$, and asset returns, $R_t$,

$$
\Delta \text{gdp}_{t+h} = \theta R_t + \epsilon_t
$$

Then the variance of the residual, $\sigma_t^2 = \text{Var}\left(\widehat{\epsilon}_t\right)$ can be estimated as,

$$
\sigma_t^2 = \exp( \delta R_t) + e_t
$$

Then the VFCI is defined as,

$$
\text{VFCI}_t = \widehat{\delta} R_t
$$

and normalized to be mean 0 and variance 1.

## Targeting VFCI Identifies Same Shock

Including VFCI in the VAR and targeting it for the max-share method returns the same business cycle shock.

[Picture of shock correlations-vfci and unemployment]


## Targeting VFCI Identifies Same Shock

The dynamics of the two shocks are also the same.

[Picture of impulse responses for select variables]


## VFCI Co-moves with the Business Cycle

We can conclude that financial conditions are co-moving with the business cycle.

. . .

But why is a financial propagation more compelling than a single belief shock?

. . .

Because we also see evidence in the VAR of a strong mean-vol relationship.

- This is present in a model with a value-at-risk constraint,
- but it is not present in a model of higher order belief shocks (needs to be confirmed).


## Mean-Vol Relationship in the VAR

Taking our VAR with $p$ lags and $k$ variables in vector $y_t$,

$$
y_t = A_1 y_{t-1} + \text{ ... } + A_p y_{t-p} + u_t
$$

The log variance of the residual is then, $V_t = \log\left(\widehat{u}_t^2\right)$.

Then estimate,

$$
V_t = \alpha_1 y_{t-1} + \text{ ... } + \alpha_p y_{t-p} + \epsilon_t
$$

The mean-vol relationship is between $\widehat{y}_t$ and $\widehat{V}_t$.

:::{.callout-note}
There are $k$ mean-vol relationships in the VAR, one for each variable.
:::


## Mean-Vol Relationship in the VAR {#mean-vol-unemployment}

Using unemployment, we can see a strong linear relationship between the conditional mean and the conditional volatility.

[picture showing mean-vol for unemp]

[[Mean-Vol for Output]{.button}](#app-mean-vol-output)


## Financial Conditions Propagating the Business Cycle

We have seen

- the existence of the mean-vol relationship in the empirical data,

- and that financial conditions moving strongly with the business cycle,

suggesting financial conditions could be the propagation mechanism.

. . .

If this is true, we would also expect a shock to financial conditions to generate the same business cycle dynamics.



## A Shock to VFCI

If we assume a Choleskey idenfication with VFCI ordered first,

then a shock to VFCI generates the same business cycle dynamics.

[Picture of the IRFs matching]


## Conclusion

Empirical facts of the business cycle are best explained by a common propagation mechanism through the financial sector.

- financial conditions move with the business cycle

- models with value-at-risk contstraint generate the empirically observed mean-volatility relationship

- shocks directly to financial conditions generate the same busines cycle


# Appendix

## Appendix: Max-Share Method Details

A SVAR(p) model with $p$ lags, for a vector of variables, $x_t$,

$$
B_0 x_t = B_1 x_{t-1} + . . . + B_p x_{t-p} + \epsilon_t
$$

Empirically, only the following $A_i$ matrices and reduced form residuals, $\nu_t$, are observed,

$$
 x_t = \underbrace{B_0^{-1}B_1}_{A_1} x_{t-1} + \dots + \underbrace{B_0^{-1}B_p}_{A_p} x_{t-p} + \underbrace{B_0^{-1}\epsilon_t}_{\upsilon_t}
$$

The identification problem is determining $B_0$.

$$
 \nu_t = B_0^{-1} \epsilon_t
$$

## Appendix: Max-Share Method Details

Compute the forecast error for one target variable (i.e. $u$) for target horizon, $h$

$$
  F_{t+h} = x^{(u)}_{t+h} - x^{(u)}_{t+h \mid t} = \sum_{i=0}^{h-1} \underbrace{\Gamma_i}_{IRF} B_0^{(u)^{-1}} \epsilon_{t+h+i}
$$

Choose vector $B_0^{(u)}$ to maximize the variance of $F_{t+h}$,

$$
  \max_{B_0^{(u)}} \ \ \ \text{Var}[F_{t+h}]
$$

This will identify **one** shock, up to a change of sign.

$$
  \epsilon_t^{u} = B_0^{(u)} \hat{\upsilon}_t
$$

For business cycle shock, calculate forecast errors over a frequency range, 6 to 32 quarters.


## Appendix: Mean-Vol Relationship in VAR {#app-mean-vol-output}

Using output instead.

[picture showing mean-vol for output]

[[Back]{.button}](#mean-vol-unemployment)