---
title: "All VAR Charts - Compare Horizons for Internal and External VFCI"
format: pdf
project:
  execute-dir: project
---

```{r}
#| include: false
library(data.table)
library(purrr)
library(vars)
library(svars)
require(fevdid)
require(ggplot2)
library(vfciBCHelpers)
library(gt)
```

```{r}
bc_freqs <- c(2 * pi / 32, 2 * pi / 6)
lags <- 2

data <- get_var_data(make_stationary = TRUE)
x <- data[, -"vfci"]

v_ext <- fit_var(data, lags = lags)
v <- fit_var(x, lags = lags)


mv_list <- list(
  max_share_u = id_fevdfd(v, "unemployment", bc_freqs),
  # vfci_ext = id_fevdfd(v, "vfci", bc_freqs),
  hr_1_c = id_linear_het_reg(v, "output", hetreg_horizon = 1, sign = "neg"),
  hr_4_c = id_linear_het_reg(v, "output", hetreg_horizon = 4, sign = "neg"),
  hr_10_c = id_linear_het_reg(v, "output", hetreg_horizon = 10, sign = "neg"),
  hr_20_c = id_linear_het_reg(v, "output", hetreg_horizon = 20, sign = "neg"),
  hr_30_c = id_linear_het_reg(v, "output", hetreg_horizon = 30, sign = "neg")
  # hr_6_c = id_linear_het_reg(v, "consumption", hetreg_horizon = 6, sign = "neg"), 
  # hr_8_c = id_linear_het_reg(v, "consumption", hetreg_horizon = 8, sign = "neg"), 
  # hr_10_c = id_linear_het_reg(v, "consumption", hetreg_horizon = 10, sign = "neg"), 
  # hr_12_c = id_linear_het_reg(v, "consumption", hetreg_horizon = 12, sign = "neg"), 
  # hr_14_c = id_linear_het_reg(v, "consumption", hetreg_horizon = 14, sign = "neg") 
)

colors <- c(
  max_share_u = "steelblue",
  # vfci_ext = "lightblue",
  hr_1_c = "lightpink",
  hr_4_c = "red",
  hr_10_c = "forestgreen",
  hr_20_c = "mediumorchid",
  hr_30_c = "goldenrod"
  # hr_6_c = "#ff0000", 
  # hr_8_c = "#ff6a00", 
  # hr_10_c = "#ffa200", 
  # hr_12_c = "#ffcc00", 
  # hr_14_c = "#95ff00"
)

```

{{< include ../all-var-charts.qmd >}}
