---
title: "Mean-Vol Heteroskedasticity Charts"
format: pdf
project:
  execute-dir: project
---

```{r}
#| include: false
library(data.table)
library(purrr)
library(vars)
library(svars)
require(fevdid)
require(ggplot2)
library(vfciBCHelpers)
```

```{r, echo = F, warning = F}
lags <- 2

add_cols <- c(
  "pc1", "pc2", "pc3", "pc4"
)

data <- get_var_data(add_cols = add_cols)
x <- data[, -"vfci"] |> copy()
v <- fit_var(x[, -c(add_cols), with = FALSE], lags = lags)

hetreg_list <- purrr::map(1:30, ~ fit_het_reg_from_var(v, hetreg_horizon = .x, x2 = add_cols, extra_data = data[, ..add_cols]))

diff_vars <- c("output", "investment", "consumption", "hours_worked", "productivity", "TFP")

var_means <-
  fitted(v) |>
  as.data.table() |> 
  _[, t := .I] |>
  tidyfast::dt_pivot_longer(-t, names_to = "variable", values_to = "mean_fitted") |>
  _[variable %in% diff_vars, mean_fitted := mean_fitted - shift(mean_fitted, 1, type = "lag"), by = .(variable)]

hetreg_dt <- purrr::map(1:30, ~ {dt <- hetreg_list[[.x]]$dt; dt$horizon = .x; dt}) |>
  purrr::list_rbind()

data <- 
  hetreg_dt |> 
  merge(var_means, by = c("t", "variable"))

```


```{r}
#| output: asis
#| echo: false

res <- map_chr(1:30, \(h) {
  knitr::knit_child(text = c(
    "## Horizon: `r h`",
    "```{r, echo = F, warning = F, fig.height = 6, out.width = '100%'}",
    "data[horizon == h] |>
    ggplot(aes(y = mean_fitted, x = log_var_fitted)) +
    geom_point() +
    facet_wrap(vars(variable), scales = 'free', nrow = 4) +
    theme_bw(base_size = 8)",
    "```",
    ""), envir = environment(), quiet = TRUE)
})
cat(res, sep = '\n')
```
