---
title: "Add Financial Data VAR Charts"
format: pdf
project:
  execute-dir: project
---

```{r}
#| include: false
library(data.table)
library(purrr)
library(vars)
library(svars)
require(fevdid)
require(ggplot2)
library(vfciBCHelpers)
```

```{r}
bc_freqs <- c(2 * pi / 32, 2 * pi / 6)
lags <- 2

fin_cols <- c(
  "pc1", "pc2", "pc3", "pc4"
)

data <- get_var_data(
  vfci_dt = est_vfci("output", fin_cols, forward = 1),
  add_cols = fin_cols,
  end_date = as.Date("2022-07-01"),
  make_stationary = FALSE
  )

x <- data[, -"vfci"] |> copy()

v <- fit_var(x[, -c(fin_cols), with = FALSE], lags = lags)
v2 <- fit_var(data[, -c(fin_cols), with = FALSE], lags = lags)

mv_list <- list(
  max_share_u = id_fevdfd(v, "unemployment", bc_freqs),
  het_reg_pc = id_linear_het_reg(
    v,
    "output",
    x2 = fin_cols,
    extra_data = data[, ..fin_cols],
    method = "mriv",
    sign = "neg"
  ),
  het_reg_pc_f12 = id_linear_het_reg(
    v,
    "output",
    hetreg_horizon = 12,
    x2 = fin_cols,
    extra_data = data[, ..fin_cols],
    method = "mriv",
    sign = "neg"
  ),
  chol = v2 |>
    reorder_var("vfci") |>
    id_ordered_chol(),
  chol_f12 = 
    get_var_data(
      vfci_dt = est_vfci("output", fin_cols, forward = 12),
      end_date = as.Date("2022-07-01"),
      make_stationary = FALSE
    ) |>
    fit_var(lags = 2) |>
    reorder_var("vfci") |>
    id_ordered_chol()
)

colors <- c(
  max_share_u = "firebrick",
  het_reg_pc = "steelblue",
  het_reg_pc_f12 = "lightblue",
  chol = "goldenrod",
  chol_f12 = "goldenrod4"
)
```

{{< include all-var-charts.qmd >}}
