---
title: "All VAR Charts"
format: pdf
project:
  execute-dir: project
---

```{r}
#| include: false
library(data.table)
library(purrr)
library(vars)
library(svars)
require(fevdid)
require(ggplot2)
library(vfciBCHelpers)
library(gt)
```

```{r}
bc_freqs <- c(2 * pi / 32, 2 * pi / 6)
lags <- 2
end_date <- as.Date("2022-07-01")

x <- get_var_data(end_date = end_date, make_stationary = TRUE)

mv_list <- list(
  max_share = 
    get_var_data(
      end_date = end_date,
      make_stationary = TRUE,
      vfci = NULL
    ) |>
    fit_var(lags = lags) |>
    id_fevdfd("unemployment", bc_freqs),
  max_share_vfci_fgr1 =
    get_var_data(
      end_date = end_date,
      make_stationary = TRUE,
      vfci_dt = est_vfci("output", c("pc1", "pc2", "pc3", "pc4"), forward = 1)
    ) |>
    fit_var(lags = lags) |>
    id_fevdfd("vfci", bc_freqs, sign = "pos"),
  max_share_vfci_fgr12 =
    get_var_data(
      end_date = end_date,
      make_stationary = TRUE,
      vfci_dt = est_vfci("output", c("pc1", "pc2", "pc3", "pc4"), forward = 12)
    ) |>
    fit_var(lags = lags) |>
    id_fevdfd("vfci", bc_freqs, sign = "neg")
)

colors <- c(
  max_share = "firebrick",
  max_share_vfci_fgr1 = "steelblue",
  max_share_vfci_fgr12 = "lightblue"
)
```

{{< include all-var-charts.qmd >}}
