---
title: "Mean-Vol Heteroskedasticity Charts"
format: pdf
project:
  execute-dir: project
---

```{r}
#| include: false
library(data.table)
library(purrr)
library(vars)
library(svars)
require(fevdid)
require(ggplot2)
library(vfciBCHelpers)
```

```{r, echo = F, warning = F, fig.height = 8, out.width = "100%", fig.cap = "Mean-Vol (twostep method, VAR means)"}
lags <- 2

data <- get_var_data()
x <- data[, -"vfci"] |> copy()
v <- fit_var(x, lags = lags)

hetreg <- fit_het_reg_from_var(v)

var_means <-
  fitted(v) |>
  as.data.table() |> 
  _[, t := .I] |>
  tidyfast::dt_pivot_longer(-t, names_to = "variable", values_to = "var_fitted")

hetreg$dt |> 
  merge(var_means, by = c("t", "variable")) |>
  ggplot(aes(y = var_fitted, x = log_var_fitted)) +
  geom_point() +
  facet_wrap(vars(variable), scales = "free", nrow = 4) +
  theme_bw(base_size = 8)
 
```

\newpage

```{r, echo = F, warning = F, fig.height = 8, out.width = "100%", fig.cap = "Mean-Vol (twostep method, adjusted means)"}

hetreg$dt |> 
  ggplot(aes(y = fitted, x = log_var_fitted)) +
  geom_point() +
  facet_wrap(vars(variable), scales = "free", nrow = 4) +
  theme_bw(base_size = 8)
 
```


\newpage

```{r, echo = F, warning = F, fig.height = 8, out.width = "100%", fig.cap = "Mean-Vol (ML method)"}

hetreg_ml <- fit_het_reg_from_var(v, hetreg_method = "ML")

hetreg_ml$dt |> 
  ggplot(aes(y = fitted, x = log_var_fitted)) +
  geom_point() +
  facet_wrap(vars(variable), scales = "free", nrow = 4) +
  theme_bw(base_size = 8)
 
```