---
title: "All VAR Charts"
output: 
    pdf_document
---

```{r setup, include = FALSE}
require(here)
require(data.table)
require(dplyr)
require(vars)
require(svars)
require(fevdid)
require(ggplot2)
```

```{r fitModels, include = T}
x <- fread(here("./data/vfciBC_data.csv")) |>
  filter(date <= as.Date("2017-01-01")) |>
  dplyr::select(
    date,
    output,
    investment,
    consumption,
    hours_worked,
    unemployment,
    labor_share,
    interest,
    inflation,
    productivity,
    TFP,
    vfci = vfci_fgr10gdpc1
  )


bc_freqs <- c(2 * pi / 32, 2 * pi / 6)
lags <- 2

v <- VAR(x[, -"date"], p = lags, type = "const")

mv_list <- list(
  U = id_fevdfd(v, "unemployment", bc_freqs),
  VFCI = id_fevdfd(v, "vfci", bc_freqs, sign = "neg")
)

colors <- c(
  U = "firebrick",
  VFCI = "steelblue"
)
```

```{r, include = F}
## IRF
irf_df <- rbindlist(lapply(seq_along(mv_list), function(i) {
  irf <- irf(mv_list[[i]], n.ahead = 40)$irf |> setDT()
  irf$model <- names(mv_list)[[i]]
  irf[impulse == "Main"]
}))

## IRF FD
irffd_df <- rbindlist(lapply(seq_along(mv_list), function(i) {
  irffd <- irffd(mv_list[[i]], n.ahead = 40)$irffd |> setDT()
  irffd$model <- names(mv_list)[[i]]
  irffd[impulse == "Main"]
}))

## FEVDFD
fevdfd_df <- rbindlist(lapply(seq_along(mv_list), function(i) {
  fevdfd <- fevdfd(mv_list[[i]])$fevdfd |> setDT()
  fevdfd$model <- names(mv_list)[[i]]
  fevdfd[impulse == "Main"]
}))

## FEVD
fevd_df <- rbindlist(lapply(seq_along(mv_list), function(i) {
  fevd <- fevd(mv_list[[i]], n.ahead = 100)$fevd |> setDT()
  fevd$model <- names(mv_list)[[i]]
  fevd[impulse == "Main"]
}))

## FEVFD
fevfd_df <- rbindlist(lapply(seq_along(mv_list), function(i) {
  fevfd <- fevfd(mv_list[[i]])$fevfd |> setDT()
  fevfd$model <- names(mv_list)[[i]]
  fevfd[impulse == "Main"]
}))

## FEV
fev_df <- rbindlist(lapply(seq_along(mv_list), function(i) {
  fev <- fev(mv_list[[i]], n_ahead = 100)$fev |> setDT()
  fev$model <- names(mv_list)[[i]]
  fev[impulse == "Main"]
}))

## HS
hs_df <- rbindlist(lapply(seq_along(mv_list), function(i) {
  hs <- hs(mv_list[[i]])$hs |> setDT()
  hs$model <- names(mv_list)[[i]]
  hs <- hs[impulse == "Main"]
  hs$date <- x[-c(1:lags), "date"][[1]]
  hs
}))

## HD
hd_df <- rbindlist(lapply(seq_along(mv_list), function(i) {
  hd <- hd(mv_list[[i]])$hd |> setDT()
  hd$model <- names(mv_list)[[i]]
  hd <- hd[impulse == "Main"]
  hd$date <- rep(x[-c(1:lags), "date"][[1]], v$K)
  hd
}))

q_df <- rbindlist(lapply(seq_along(mv_list), function(i) {
  data.table(
    variable = colnames(mv_list[[i]]$y),
    weight = mv_list[[i]]$Q[, 1],
    model = names(mv_list)[[i]]
  )
}))

b_df <- rbindlist(lapply(seq_along(mv_list), function(i) {
  data.table(
    variable = colnames(mv_list[[i]]$y),
    weight = mv_list[[i]]$B[, 1],
    model = names(mv_list)[[i]]
  )
}))

```


```{r plot_irf, echo = F, warning = F, fig.height = 5, out.width = "100%", fig.cap = "IRF"}
irf_df |>
  ggplot(aes(
    x = h,
    y = irf,
    color = model
  )) +
  geom_hline(yintercept = 0) +
  geom_line() +
  facet_wrap(
    vars(response),
    nrow = 3,
    scales = "free_y"
  ) +
  scale_color_manual(
    values = colors
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```

\newpage

```{r plot_irffd, echo = F, warning = F, fig.height = 3.25, out.width = "100%", fig.cap = "IRF Frequency Domain"}
irffd_df[f <= pi] |>
  ggplot(aes(
    x = f,
    y = irf,
    color = model
  )) +
  geom_rect(
    ymin = -Inf,
    ymax = Inf,
    xmin = 2 * pi / 32,
    xmax = 2 * pi / 6,
    fill = "gray90",
    color = NA
  ) +
  geom_hline(yintercept = 0) +
  geom_line() +
  facet_wrap(
    vars(response),
    nrow = 3,
    scales = "free_y"
  ) +
  scale_color_manual(
    values = colors
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```

```{r plot_irffd2, echo = F, warning = F, fig.height = 3.25, out.width = "100%", fig.cap = "IRF Frequency Domain (<= 2 pi /6)"}
irffd_df[f <=  2 * pi / 6] |>
  ggplot(aes(
    x = f,
    y = irf,
    color = model
  )) +
  geom_rect(
    ymin = -Inf,
    ymax = Inf,
    xmin = 2 * pi / 32,
    xmax = 2 * pi / 6,
    fill = "gray90",
    color = NA
  ) +
  geom_hline(yintercept = 0) +
  geom_line() +
  facet_wrap(
    vars(response),
    nrow = 3,
    scales = "free_y"
  ) +
  scale_color_manual(
    values = colors
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```


```{r plot_fevdfd, echo = F, warning = F, fig.height = 5, out.width = "100%", fig.cap = "FEVDFD"}
fevdfd_df[f <= pi] |>
  ggplot(aes(
    x = f,
    y = fevdfd,
    color = model
  )) +
  geom_rect(
    ymin = -Inf,
    ymax = Inf,
    xmin = 2 * pi / 32,
    xmax = 2 * pi / 6,
    fill = "gray90",
    color = NA
  ) +
  geom_line() +
  facet_wrap(
    vars(response),
    nrow = 3,
    scales = "free_y"
  ) +
  scale_color_manual(
    values = colors
  ) +
  scale_y_continuous(
    limits = c(0, 1)
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```


```{r plot_fevd, echo = F, warning = F, fig.height = 5, out.width = "100%", fig.cap = "FEVD"}
fevd_df |>
  ggplot(aes(
    x = h,
    y = fevd / 100,
    color = model
  )) +
  geom_line() +
  facet_wrap(
    vars(response),
    nrow = 3,
    scales = "free_y"
  ) +
  scale_color_manual(
    values = colors
  ) +
  scale_y_continuous(
    limits = c(0, 1)
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```


```{r plot_fevfd, echo = F, warning = F, fig.height = 5, out.width = "100%", fig.cap = "FEV FD"}
fevfd_df[f <= pi] |>
  ggplot(aes(
    x = f,
    y = fevfd,
    color = model
  )) +
  geom_rect(
    ymin = -Inf,
    ymax = Inf,
    xmin = 2 * pi / 32,
    xmax = 2 * pi / 6,
    fill = "gray90",
    color = NA
  ) +
  geom_line() +
  facet_wrap(
    vars(response),
    nrow = 3,
    scales = "free_y"
  ) +
  scale_color_manual(
    values = colors
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```


```{r plot_fev, echo = F, warning = F, fig.height = 5, out.width = "100%", fig.cap = "FEV"}
fev_df |>
  ggplot(aes(
    x = h,
    y = fev ,
    color = model
  )) +
  geom_line() +
  facet_wrap(
    vars(response),
    nrow = 3,
    scales = "free_y"
  ) +
  scale_color_manual(
    values = colors
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```

```{r plot_hs, echo = F, warning = F, fig.height = 5, out.width = "100%", fig.cap = "Historical Shocks"}
hs_df |>
  ggplot(aes(
    x = date,
    y = hs,
    color = model
  )) +
  geom_hline(yintercept = 0) +
  geom_line() +
  scale_color_manual(
    values = colors
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```

```{r plot_hd, echo = F, warning = F, fig.height = 8, out.width = "100%", fig.cap = "Historical Shocks"}
hd_df |>
  ggplot(aes(
    x = date,
    y = hd,
    color = model
  )) +
  geom_hline(yintercept = 0) +
  geom_line() +
  facet_wrap(
    vars(response),
    ncol = 2,
    scales = "free_y"
  ) +
  scale_color_manual(
    values = colors
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```

```{r plot_q, echo = F, warning = F, fig.height = 3.25, out.width = "100%", fig.cap = "Q Weights (Rotation)"}
q_df |>
  ggplot(aes(
    x = variable,
    y = weight,
    fill = model
  )) +
  geom_hline(yintercept = 0) +
  geom_col(
    position = position_dodge()
  ) +
  scale_fill_manual(
    values = colors
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```

```{r plot_b, echo = F, warning = F, fig.height = 3.25, out.width = "100%", fig.cap = "B Weights (Empirical Shocks)"}
b_df |>
  ggplot(aes(
    x = variable,
    y = weight,
    fill = model
  )) +
  geom_hline(yintercept = 0) +
  geom_col(
    position = position_dodge()
  ) +
  scale_fill_manual(
    values = colors
  ) +
  theme_bw(base_size = 8) +
  theme(legend.position = "top")
```