on:
  push:
    paths:
      - code/vfciBCHelpers/**
  workflow_dispatch:

name: Check vfciBCHelpers

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: dependencies on Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y make libicu-dev libxml2-dev libssl-dev pandoc librdf0-dev libnode-dev libcurl4-gnutls-dev
          sudo apt install libharfbuzz-dev libfribidi-dev

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Run R CMD Check
        run: |
          Rscript -e 'renv::install(c("devtools", "bvartools", "data.table", "tidyfast", "vars")); renv::install("vfci/fevdid"); devtools::check("./code/vfciBCHelpers")'